name: CI

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  emulator_test:
    name: Run all tests using Firebase Emulator Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "npm"
      - name: Install Firebase Emulator Suite
        run: npm install -g firebase-tools
      - name: Install npm dependencies
        run: npm ci
      - name: Build code
        run: npm run build
      - name: Cache firebase emulators
        uses: actions/cache@v2
        with:
          path: ~/.cache/firebase/emulators
          key: ${{ runner.os }}-firebase-emulators-${{ hashFiles('~/.cache/firebase/emulators/**') }}
        continue-on-error: true
      - name: Run all the tests
        run: firebase emulators:exec --project demo-nhogs-nestjs-firebase --import=test/e2e/import 'npm test'
      - name: Send coverage report
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
