name: Firebase CI

on: push

jobs:
  emulator_test:
    name: Run all tests using Firebase Emulator Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install Firebase Emulator Suite
        run: npm install -g firebase-tools
      - name: Install npm dependencies
        run: npm ci
      - name: Build code
      - run: npm run build
      - name: Run all the tests
        run: firebase emulators:exec 'npm test'
